micronaut:
    server:
        cors:
            enabled: true
            configurations:
                all-prod:
                    allowed-origins: https://ec2.chp1.net
                    allowedMethods:
                        - GET
                        - POST
                        - PUT
                    allowedHeaders:
                        - Authorization
                    allowCredentials: true
                    maxAge: 1800 # 30 min
